# The MIT License (MIT)

# Copyright (c) 2016-2024 Objectionary.com

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
report:
  output:
    html: pipeline/report/report.html
    json: pipeline/report/report.json
    markdown: pipeline/report/report.md
  expected-metrics-change:
    dataless: 0.2
    applications: 0.2
    formations: 0.1
    dispatches: 0.2
  expected-improved-programs-percentage: 0.9
test-sets:
  - common:
      path-prefix:
        eo:
          original: eo/eo-runtime/src/test/eo/org/eolang
          yaml: pipeline/eo-yaml
          filtered: pipeline/eo-filtered
        phi:
          initial: pipeline/phi-initial
          normalized: pipeline/phi-normalized
      bindings-path: org.eolang
    individual:
      - name: as-phi-tests
        enable: false
      - name: as-phi-tests
        enable: false
      - name: bool-tests
        exclude:
          # broken
          - compares-bool-to-string
          # too slow
          - forks-on-false-condition
          - forks-on-true-condition
          - true-and-false-is-false
          - true-as-bool
          - true-not-is-false
      - name: bytes-tests
        exclude:
          # broken
          - counts-size-of-bytes
          - size-of-part-is-correct
          - written-in-several-lines
          - left-with-even-neg
          - takes-part-of-bytes
          # too slow
          - and-neg-bytes-as-number-with-leading-zeroes
          - and-neg-bytes-as-number-without-leading-zeroes
          - bitwise-works
          - bitwise-works-negative
          - bytes-as-i64-as-bytes-not-eq-to-number-as-bytes
          - bytes-converts-to-i64
          - bytes-converts-to-i64-and-back
          - one-xor-one-as-number
          - or-neg-bytes-as-number-with-zero
          - throws-on-bytes-of-wrong-size-as-i64
          - throws-on-bytes-of-wrong-size-as-number
          - xor-neg-bytes-as-number-without-leading-zeroes
      - name: cage-tests
        enable: false
      - name: cti-test
        enable: false
      - name: dataized-tests
        enable: false
      - name: fs/dir-tests
        enable: false
      - name: fs/file-tests
        enable: false
      - name: fs/path-tests
        enable: false
      - name: fs/tmpdir-tests
        enable: false
      - name: go-tests
        enable: false
      - name: i16-tests
        enable: false
      - name: i32-tests
        enable: false
      - name: i64-tests
        exclude:
          # broken
          - negative-i64-to-i32-and-back
          - i64-as-bytes-is-not-equal-to-number-bytes
          # too slow
          - i64-div-less-than-i64-one
          - i64-eq-false
          - i64-eq-true
          - i64-gte-equal
          - i64-gte-false
          - i64-gte-true
          - i64-has-valid-bytes
          - i64-less-equal
          - i64-less-false
          - i64-less-true
          - i64-lte-equal
          - i64-lte-false
          - i64-lte-true
          - i64-multiply-by-zero
          - i64-one-minus-i64-one
          - i64-one-plus-i64-one
          - i64-to-i32-and-back
          - i64-zero-eq-to-i64-zero
          - throws-on-converting-to-i32-if-out-of-bounds
          - throws-on-division-i64-by-i64-zero
      - name: io/bytes-as-input-test
        enable: false
      - name: io/dead-input-tests
      - name: io/dead-output-tests
      - name: io/input-length-tests
        enable: false
      - name: io/malloc-as-output-test
        enable: false
      - name: io/tee-input-tests
        enable: false
      - name: malloc-tests
        enable: false
      - name: math/angle-tests
        enable: false
      - name: math/integral-tests
        enable: false
      - name: math/numbers-tests
        enable: false
      - name: math/random-tests
        enable: false
      - name: math/real-tests
        enable: false
      - name: nan-tests
        exclude:
          # broken
          - nan-as-bytes-is-bytes-of-zero-div-zero
          # too slow
          - nan-is-nan
          - nan-is-not-finite
          - nan-is-not-integer
          - nan-neg-is-nan
          - nan-not-eq-nan
      - name: negative-infinity-tests
        exclude:
          # too slow
          - negative-infinity-div-float-zero
          - negative-infinity-div-int-zero
          - negative-infinity-div-nan
          - negative-infinity-div-neg-float-zero
          - negative-infinity-div-neg-int-zero
          - negative-infinity-div-negative-float
          - negative-infinity-div-negative-infinity
          - negative-infinity-div-negative-int
          - negative-infinity-div-positive-float
          - negative-infinity-div-positive-infinity
          - negative-infinity-div-positive-int
          - negative-infinity-eq-negative-infinity
          - negative-infinity-floor-is-equal-to-self
          - negative-infinity-gt-negative-infinity
          - negative-infinity-is-not-finite
          - negative-infinity-is-not-integer
          - negative-infinity-is-not-nan
          - negative-infinity-lt-float
          - negative-infinity-lt-int
          - negative-infinity-lt-negative-infinity
          - negative-infinity-lt-positive-infinity
          - negative-infinity-lte-float
          - negative-infinity-lte-int
          - negative-infinity-lte-negative-infinity
          - negative-infinity-lte-positive-infinity
          - negative-infinity-minus-nan
          - negative-infinity-minus-negative-float
          - negative-infinity-minus-negative-infinity
          - negative-infinity-minus-negative-int
          - negative-infinity-minus-positive-float
          - negative-infinity-minus-positive-infinity
          - negative-infinity-minus-positive-int
          - negative-infinity-neg-is-positive-infinity
          - negative-infinity-not-eq-nan
          - negative-infinity-not-eq-positive-infinity
          - negative-infinity-not-lt-nan
          - negative-infinity-not-lte-nan
          - negative-infinity-plus-nan
          - negative-infinity-plus-negative-float
          - negative-infinity-plus-negative-infinity
          - negative-infinity-plus-negative-int
          - negative-infinity-plus-positive-float
          - negative-infinity-plus-positive-infinity
          - negative-infinity-plus-positive-int
          - negative-infinity-times-float-zero
          - negative-infinity-times-int-zero
          - negative-infinity-times-nan
          - negative-infinity-times-neg-float-zero
          - negative-infinity-times-negative-float
          - negative-infinity-times-negative-infinity
          - negative-infinity-times-negative-int
          - negative-infinity-times-positive-float
          - negative-infinity-times-positive-infinity
          - negative-infinity-times-positive-int
        enable: false
      - name: number-tests
        enable: false
      - name: positive-infinity-tests
        exclude:
          # too slow
          - float-equal-to-nan-and-infinites-is-false-highload
          - positive-infinity-div-float-zero
          - positive-infinity-div-int-zero
          - positive-infinity-div-nan
          - positive-infinity-div-neg-float-zero
          - positive-infinity-div-neg-int-zero
          - positive-infinity-div-negative-float
          - positive-infinity-div-negative-infinity
          - positive-infinity-div-negative-int
          - positive-infinity-div-positive-float
          - positive-infinity-div-positive-infinity
          - positive-infinity-div-positive-int
          - positive-infinity-eq-positive-infinity
          - positive-infinity-floor-is-equal-to-self
          - positive-infinity-gt-float
          - positive-infinity-gt-int
          - positive-infinity-gt-negative-infinity
          - positive-infinity-gt-positive-infinity
          - positive-infinity-gte-float
          - positive-infinity-gte-int
          - positive-infinity-gte-negative-infinity
          - positive-infinity-gte-positive-infinity
          - positive-infinity-is-not-finite
          - positive-infinity-is-not-integer
          - positive-infinity-is-not-nan
          - positive-infinity-minus-nan
          - positive-infinity-minus-negative-float
          - positive-infinity-minus-negative-infinity
          - positive-infinity-minus-negative-int
          - positive-infinity-minus-positive-float
          - positive-infinity-minus-positive-infinity
          - positive-infinity-minus-positive-int
          - positive-infinity-neg-is-negative-infinity
          - positive-infinity-not-eq-nan
          - positive-infinity-not-eq-negative-infinity
          - positive-infinity-not-gt-nan
          - positive-infinity-not-gte-nan
          - positive-infinity-plus-nan
          - positive-infinity-plus-negative-infinity
          - positive-infinity-plus-positive-float
          - positive-infinity-plus-positive-infinity
          - positive-infinity-times-float-zero
          - positive-infinity-times-int-zero
          - positive-infinity-times-nan
          - positive-infinity-times-neg-float-zero
          - positive-infinity-times-negative-float
          - positive-infinity-times-negative-infinity
          - positive-infinity-times-negative-int
          - positive-infinity-times-positive-float
          - positive-infinity-times-positive-infinity
          - positive-infinity-times-positive-int
        enable: false
      - name: runtime-tests
        enable: false
      - name: rust-tests
        enable: false
      - name: seq-tests
        enable: false
      - name: string-tests
        exclude:
          # broken
          - throws-on-slicing-end-below-start
          - slice-escape-sequences-line-break
          - slice-escape-sequences-unicode
          - throws-on-slicing-start-below-zero
          - bytes-equal-to-string
          - no-slice-string
          - reads-the-length-with-2-byte-characters
          - reads-the-length-with-3-byte-characters
          - reads-the-length-with-4-byte-characters
          - slice-empty-string
          - string-equals-to-bytes
          - text-block-tree-lines
          - text-block-with-margin
          - turns-string-into-bytes
          - slice-with-2-byte-characters
          - slice-with-3-byte-characters
          - slice-with-4-byte-characters
          # too slow
          - slice-foreign-literals
          - slice-foreign-literals-2
          - slice-from-start
          - slice-from-the-end
          - slice-in-the-middle
          - throws-on-slicing-end-greater-actual
          - calculates-length-of-spaces-only
          - reads-the-length
      - name: structs/bytes-as-array-tests
        enable: false
      - name: structs/hash-code-of-tests
        enable: false
      - name: structs/list-tests
        enable: false
      - name: structs/map-tests
        enable: false
      - name: structs/range-of-ints-tests
        enable: false
      - name: structs/range-tests
        enable: false
      - name: structs/set-tests
        enable: false
      - name: switch-tests
        enable: false
      - name: sys/os-tests
        enable: false
      - name: sys/posix-tests
        enable: false
      - name: sys/win32-tests
        enable: false
      - name: try-tests
        enable: false
      - name: tuple-tests
        enable: false
      - name: txt/regex-tests
        enable: false
      - name: txt/sprintf-tests
        enable: false
      - name: txt/sscanf-tests
        enable: false
      - name: txt/text-tests
        enable: false
      - name: while-tests
        exclude:
          # broken
          - iterating-tuple-with-while-using-external-iterator
          # too slow
          - iterating-tuple-with-while-using-internal-iterator
          - iterating-tuple-with-while-without-body-multiple
          - iterating-tuple-with-while-without-body-single
          - last-while-dataization-object
          - simple-bool-expression-via-malloc-in-while
          - simple-while-with-false-first
          - while-dataizes-only-first-cycle
          - while-simple-iteration
