report:
  output:
    html: pipeline/report/report.html
    json: pipeline/report/report.json
    markdown: pipeline/report/report.md
  expected-metrics-change:
    dataless: 0.2
    applications: 0.2
    formations: 0.1
    dispatches: 0.2
  expected-improved-programs-percentage: 0.9
test-sets:
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/as-phi-tests.eo
    yaml: pipeline/eo-yaml/as-phi-tests.yaml
    filtered: pipeline/eo-filtered/as-phi-tests.eo
  phi:
    initial: pipeline/phi-initial/as-phi-tests.phi
    normalized: pipeline/phi-normalized/as-phi-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/bool-tests.eo
    yaml: pipeline/eo-yaml/bool-tests.yaml
    filtered: pipeline/eo-filtered/bool-tests.eo
  phi:
    initial: pipeline/phi-initial/bool-tests.phi
    normalized: pipeline/phi-normalized/bool-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/bytes-tests.eo
    yaml: pipeline/eo-yaml/bytes-tests.yaml
    filtered: pipeline/eo-filtered/bytes-tests.eo
  phi:
    initial: pipeline/phi-initial/bytes-tests.phi
    normalized: pipeline/phi-normalized/bytes-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/cage-tests.eo
    yaml: pipeline/eo-yaml/cage-tests.yaml
    filtered: pipeline/eo-filtered/cage-tests.eo
  phi:
    initial: pipeline/phi-initial/cage-tests.phi
    normalized: pipeline/phi-normalized/cage-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/cti-test.eo
    yaml: pipeline/eo-yaml/cti-test.yaml
    filtered: pipeline/eo-filtered/cti-test.eo
  phi:
    initial: pipeline/phi-initial/cti-test.phi
    normalized: pipeline/phi-normalized/cti-test.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/dataized-tests.eo
    yaml: pipeline/eo-yaml/dataized-tests.yaml
    filtered: pipeline/eo-filtered/dataized-tests.eo
  phi:
    initial: pipeline/phi-initial/dataized-tests.phi
    normalized: pipeline/phi-normalized/dataized-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/float-tests.eo
    yaml: pipeline/eo-yaml/float-tests.yaml
    filtered: pipeline/eo-filtered/float-tests.eo
  phi:
    initial: pipeline/phi-initial/float-tests.phi
    normalized: pipeline/phi-normalized/float-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/goto-tests.eo
    yaml: pipeline/eo-yaml/goto-tests.yaml
    filtered: pipeline/eo-filtered/goto-tests.eo
  phi:
    initial: pipeline/phi-initial/goto-tests.phi
    normalized: pipeline/phi-normalized/goto-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/int-tests.eo
    yaml: pipeline/eo-yaml/int-tests.yaml
    filtered: pipeline/eo-filtered/int-tests.eo
  phi:
    initial: pipeline/phi-initial/int-tests.phi
    normalized: pipeline/phi-normalized/int-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/io/stdout-tests.eo
    yaml: pipeline/eo-yaml/io/stdout-tests.yaml
    filtered: pipeline/eo-filtered/io/stdout-tests.eo
  phi:
    initial: pipeline/phi-initial/io/stdout-tests.phi
    normalized: pipeline/phi-normalized/io/stdout-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/malloc-tests.eo
    yaml: pipeline/eo-yaml/malloc-tests.yaml
    filtered: pipeline/eo-filtered/malloc-tests.eo
  phi:
    initial: pipeline/phi-initial/malloc-tests.phi
    normalized: pipeline/phi-normalized/malloc-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/nan-tests.eo
    yaml: pipeline/eo-yaml/nan-tests.yaml
    filtered: pipeline/eo-filtered/nan-tests.eo
  phi:
    initial: pipeline/phi-initial/nan-tests.phi
    normalized: pipeline/phi-normalized/nan-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/negative-infinity-tests.eo
    yaml: pipeline/eo-yaml/negative-infinity-tests.yaml
    filtered: pipeline/eo-filtered/negative-infinity-tests.eo
  phi:
    initial: pipeline/phi-initial/negative-infinity-tests.phi
    normalized: pipeline/phi-normalized/negative-infinity-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/positive-infinity-tests.eo
    yaml: pipeline/eo-yaml/positive-infinity-tests.yaml
    filtered: pipeline/eo-filtered/positive-infinity-tests.eo
  phi:
    initial: pipeline/phi-initial/positive-infinity-tests.phi
    normalized: pipeline/phi-normalized/positive-infinity-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/runtime-tests.eo
    yaml: pipeline/eo-yaml/runtime-tests.yaml
    filtered: pipeline/eo-filtered/runtime-tests.eo
  phi:
    initial: pipeline/phi-initial/runtime-tests.phi
    normalized: pipeline/phi-normalized/runtime-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/rust-tests.eo
    yaml: pipeline/eo-yaml/rust-tests.yaml
    filtered: pipeline/eo-filtered/rust-tests.eo
  phi:
    initial: pipeline/phi-initial/rust-tests.phi
    normalized: pipeline/phi-normalized/rust-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
  enable: false
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/seq-tests.eo
    yaml: pipeline/eo-yaml/seq-tests.yaml
    filtered: pipeline/eo-filtered/seq-tests.eo
  phi:
    initial: pipeline/phi-initial/seq-tests.phi
    normalized: pipeline/phi-normalized/seq-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
  enable: false
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/string-tests.eo
    yaml: pipeline/eo-yaml/string-tests.yaml
    filtered: pipeline/eo-filtered/string-tests.eo
  phi:
    initial: pipeline/phi-initial/string-tests.phi
    normalized: pipeline/phi-normalized/string-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/switch-tests.eo
    yaml: pipeline/eo-yaml/switch-tests.yaml
    filtered: pipeline/eo-filtered/switch-tests.eo
  phi:
    initial: pipeline/phi-initial/switch-tests.phi
    normalized: pipeline/phi-normalized/switch-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/try-tests.eo
    yaml: pipeline/eo-yaml/try-tests.yaml
    filtered: pipeline/eo-filtered/try-tests.eo
  phi:
    initial: pipeline/phi-initial/try-tests.phi
    normalized: pipeline/phi-normalized/try-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/tuple-tests.eo
    yaml: pipeline/eo-yaml/tuple-tests.yaml
    filtered: pipeline/eo-filtered/tuple-tests.eo
  phi:
    initial: pipeline/phi-initial/tuple-tests.phi
    normalized: pipeline/phi-normalized/tuple-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
- eo:
    original: eo/eo-runtime/src/test/eo/org/eolang/while-tests.eo
    yaml: pipeline/eo-yaml/while-tests.yaml
    filtered: pipeline/eo-filtered/while-tests.eo
  phi:
    initial: pipeline/phi-initial/while-tests.phi
    normalized: pipeline/phi-normalized/while-tests.phi
    bindings-path-initial: org.eolang
    bindings-path-normalized: org.eolang
