[book]
authors = ["Danila Danko"]
language = "en"
multilingual = false
src = "src"
title = "phi-normalizer"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
mathjax-support = true
git-repository-url = "https://github.com/objectionary/eo-phi-normalizer"
git-repository-icon = "fa-github"

[build]
build-dir = "./docs"

[output.linkcheck]
