# @todo #1326:30min Enable only necessary tests. Several checks
#  are not available for the project. For example a lot of
#  package name contains capital letter and such names are conventional.
exclude_paths:
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOas_phi.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObool$EOif.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObool$EOwhile.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOand.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOas_float.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOas_int.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOas_string.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOconcat.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOeq.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOnot.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOor.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOright.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOsize.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOslice.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EObytes$EOxor.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOdiv.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOgt.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOplus.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOfloat$EOtimes.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOdiv.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOgt.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOplus.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOint$EOtimes.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOio/EOstdin$EOnext_line.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOram$EOram_slice$EOwrite.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOram$EOslice.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOram$EOwrite.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOas_bytes.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOlength.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOstring$EOslice.java"
  - "eo-runtime/src/main/java/EOorg/EOeolang/EOheap$EOpointer$EOblock.java"