name: daily
on:
  schedule:
    # Run load testing at 01:30 UTC every day
    - cron: '30 1 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: teatimeguest/setup-texlive-action@v3.0.2
        with:
          update-all-packages: true
          packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: |
          # Clean the test classes to avoid caching issues and prepare testing environment
          # without running the tests
          mvn clean install -Pqulice -DskipTests -DskipITs -Dinvoker.skip=true
          # Find script
          SCRIPT="${GITHUB_WORKSPACE}/src/test/scripts/test-repetition.sh"
          # Check that script is exists
          if [ ! -f "${SCRIPT}" ]; then
              echo "Script ${SCRIPT} not found"
              exit 1
          fi
          # Make script runnable
          chmod +x "${SCRIPT}"
          # Test eo-parser
          ${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-parser
          # Test eo-maven-plugin
          ${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-maven-plugin
          # Test eo-runtime
          ${SCRIPT} --max 10 --folder ${GITHUB_WORKSPACE}/eo-runtime --compilation true
  report-fail:
    name: Create issue on failure
    needs: build
    if: failure() && github.even.pull_request == null
    runs-on: ubuntu-22.04
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
