---
name: ebnf
on:
  push:
    paths-ignore: ['paper/**', 'sandbox/**']
  pull_request:
    branches:
      - master
    paths-ignore: [ 'paper/**', 'sandbox/**' ]
jobs:
  ebnf:
    runs-on: ubuntu-22.04
    env:
      CONVERT_PATH: /tmp/antlr4-to-bnf-converter
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: |
          sudo apt-get update
          sudo apt-get -y install ghostscript imagemagick texlive-extra-utils pdf2svg inkscape
      - uses: teatimeguest/setup-texlive-action@v3.0.2
        with:
          update-all-packages: true
          packages: scheme-basic geometry xcolor naive-ebnf microtype etoolbox
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 20
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: |
          mkdir -p "$CONVERT_PATH"
          wget --quiet http://public.yegor256.com/convert.zip -O /tmp/convert.zip
          unzip -o -d "$CONVERT_PATH" /tmp/convert.zip
      - run: sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
      - run: |
          mvn com.yegor256:antlr2ebnf-maven-plugin:0.0.7:generate \
            -pl :eo-parser --errors --batch-mode --quiet \
            "-Dantlr2ebnf.convertDir=$CONVERT_PATH" \
            "-Dantlr2ebnf.specials=eof,eol,eop,tab,untab" \
            "-Dantlr2ebnf.margin=40"
      - run: |
          convert --version
          convert --help | grep Delegates
          pdfcrop --version
          set -x
          for p in Eo Phi; do
            cp "eo-parser/target/ebnf/org/eolang/parser/${p}.pdf" .
            pdfcrop --margins '10 10 10 10' "${p}.pdf" "${p}-cropped.pdf"
            pdf2svg "${p}-cropped.pdf" "${p}.svg"
            convert -verbose -density 300 -quality 100 -colorspace RGB "${p}.svg" "${p}.png"
            mkdir -p gh-pages/ebnf
            cp "${p}.png" gh-pages/ebnf
            cp "${p}.svg" gh-pages/ebnf
          done
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
        if: github.ref == 'refs/heads/master'
