---
name: shellcheck
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: shellcheck-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
